version: '3.8'

services:
  nodejs_backend:
    image: sissoo/updated-nodejs-backend
    env_file: .env
    container_name: nodejs_backend-containerr1
    restart: always
    expose:
      - 4000

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs_backend
